server:
  port: 8888

spring:
  profiles:
    active: dev, docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VolodymyrStupin/car-service-microservices-config
          default-label: main
