server:
  port: 8001
spring:
  application:
    name: car-service-workshop-service

#Logging properties
logging:
  level:
    org:
      springframework: info
    com:
      stupin: debug
  file:
    path: ./logs
    name: ${logging.file.path}/application.log